---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ application }}-{{ environment }}-cert
  namespace: ps2alerts
spec:
  secretName: {{ application }}-{{ environment }}-cert
  commonName: {{ hostname }}
  dnsNames:
    - {{ hostname }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ application }}-{{ environment }}
  namespace: ps2alerts
  annotations:
    nginx.ingress.kubernetes.io/server-snippet: |
      expires 1d;
      add_header Cache-Control "public, must-revalidate";
spec:
  ingressClassName: istio
  tls:
    - hosts:
        - "{{ hostname }}"
      secretName: {{ application }}-{{ environment }}-cert
  rules:
      - host: "{{ hostname }}"
        http:
          paths:
            - pathType: Prefix
              path: "/"
              backend:
                service:
                  name: {{ application }}-{{ environment }}
                  port:
                    number: {{ port }}
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ application }}-{{ environment }}
  namespace: ps2alerts
spec:
  selector:
    istio: ingress
  servers:
    - hosts:
      - {{ hostname }}
      port:
        name: https
        number: 443
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: {{ application }}-{{ environment }}-cert
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ application }}-{{ environment }}
  namespace: ps2alerts
spec:
  hosts:
    - {{ hostname }}
  gateways:
    - {{ application }}-{{ environment }}
  http:
    - route:
      - destination:
          host: {{ application }}-{{ environment }}
          port:
            number: {{ port }}
