---
- hosts: localhost
  vars_files:
    - "{{ playbook_dir }}/../vars.yml"
  #    - "{{ playbook_dir }}/../vars_local.yml"
  tasks:
    - debug:
        msg: "========= 🔗 Starting API Module 🔗 ========="

    - name: Delete dist folder
      file:
        path: "{{ root_dir }}/dist"
        state: absent

    - name: Start API Dev Image
      docker_container:
        name: ps2alerts-api
        image: ps2alerts/api:dev
        state: started
        restart: no
        recreate: yes
        restart_policy: "no"
        volumes:
          - "{{ root_dir | realpath }}:/app:rw"
        networks:
          - name: "ps2alerts"
        networks_cli_compatible: no
        tty: true
        ports:
          - "3000"
        env:
          NODE_ENV: "development"
          VERSION: "12345"
          HTTP_PORT: "3000"
          DB_HOST: "ps2alerts-db"
          DB_PORT: "27017"
          DB_USER: "root"
          DB_PASS: "foobar"
          DB_NAME: "ps2alerts"
          DB_DEBUG: "true"
          REDIS_HOST: "ps2alerts-redis"
          REDIS_PORT: "6379"
          REDIS_DB: "1"
          RABBITMQ_HOST: "ps2alerts-mq"
          AGGREGATOR_ENABLED: "true"
          CRON_ENABLED: "true"
        labels:
          traefik.enable: "true"
          traefik.http.routers.ps2alerts_api.rule: "Host(`dev.api.ps2alerts.com`)"
          traefik.http.routers.ps2alerts_api.service: "ps2alerts_api_service"
          traefik.http.services.ps2alerts_api_service.loadbalancer.server.port: "3000"
          traefik.http.services.ps2alerts_api_service.loadbalancer.server.scheme: "http"
          traefik.http.services.ps2alerts_api_service.loadbalancer.passhostheader: "true"
