---
apiVersion: v1
kind: Service
metadata:
  name: {{ application }}-{{ environment }}
  namespace: ps2alerts
  labels:
    app: {{ application }}-{{ environment }}
spec:
  selector:
    app: {{ application }}-{{ environment }}
  ports:
    - protocol: TCP
      port: {{ port }}
      targetPort: {{ port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ application }}-{{ environment }}
  namespace: ps2alerts
  labels:
    app: {{ application }}-{{ environment }}
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ application }}-{{ environment }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ application }}-{{ environment }}
        version: {{ version }}
    spec:
      containers:
        - name: application
          image: maelstromeous/applications:{{ application }}-{{ environment }}-{{ version }}
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "300m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "256Mi"
          startupProbe:
            httpGet:
              path: /healthcheck
              port: {{ port }}
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 9 # 90 seconds, takes normally about 20s
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: {{ port }}
            periodSeconds: 5
            successThreshold: 2 # Requires 2 confirms
            failureThreshold: 6 # If unready for 30s after startup
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: {{ port }}
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 2 # If dead for 20s
            timeoutSeconds: 5
            terminationGracePeriodSeconds: 15
          env:
            - name: NODE_ENV
              value: "{{ environment }}"
            - name: VERSION
              value: "{{ version }}"
            - name: DB_USER
              value: "{{ db_user }}"
            - name: DB_PASS
              value: "{{ db_pass }}"
            - name: DB_HOST
              value: "ps2alerts-db"
            - name: DB_PORT
              value: "27017"
            - name: DB_NAME
              value: "{{ db_name }}"
            - name: DB_DEBUG
              value: "false"
            - name: DB_POOL_SIZE
              value: "{{ db_pool_size }}"
            - name: RABBITMQ_HOST
              value: "ps2alerts-rabbitmq"
            - name: RABBITMQ_USER
              value: "ps2alerts"
            - name: RABBITMQ_PASS
              value: "{{ rabbitmq_pass }}"
            - name: RABBITMQ_VHOST
              value: "/ps2alerts"
            - name: RABBITMQ_QUEUE
              value: "{{ rabbitmq_queue }}"
            - name: RABBITMQ_PREFETCH
              value: "{{ rabbitmq_prefetch }}"
            - name: REDIS_HOST
              value: "{{ redis_host }}"
            - name: REDIS_PASS
              value: "{{ redis_pass }}"
            - name: REDIS_DB
              value: "{{ redis_db }}"
            - name: AGGREGATOR_ENABLED
              value: "true"
            - name: CRON_ENABLED
              value: "false"
            - name: LOGGER_TRANSPORTS
              value: "console"
            - name: INTERNAL_API_USER
              value: "{{ internal_api_user }}"
            - name: INTERNAL_API_PASS
              value: "{{ internal_api_pass }}"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ application }}-{{ environment }}
  namespace: ps2alerts
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ application }}-{{ environment }}
  minReplicas: {{ min_replicas }}
  maxReplicas: {{ max_replicas }}
  targetCPUUtilizationPercentage: 70
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ application }}-{{ environment }}
  namespace: ps2alerts
  labels:
    app: {{ application }}
spec:
  selector:
    matchLabels:
      app: {{ application }}-{{ environment }}
  endpoints:
    - port: "{{ port }}"
