apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ application }}-{{ environment }}
  namespace: ps2alerts
  labels:
    app: {{ application }}-{{ environment }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ application }}-{{ environment }}
  template:
    metadata:
      labels:
        app: {{ application }}-{{ environment }}
        version: {{ version }}
    spec:
      containers:
        - name: application
          image: maelstromeous/ps2alerts:ps2alerts-api-{{ environment }}-{{ version }}
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "250m"
              memory: "150Mi"
            limits:
              cpu: "750m"
              memory: "300Mi"
          env:
            - name: NODE_ENV
              value: "{{ environment }}"
            - name: VERSION
              value: "{{ version }}"
            - name: DB_USER
              value: "{{ db_user }}"
            - name: DB_PASS
              value: "{{ db_pass }}"
            - name: DB_HOST
              value: "ps2alerts-db"
            - name: DB_PORT
              value: "27017"
            - name: DB_NAME
              value: "{{ db_name }}"
            - name: DB_DEBUG
              value: "false"
            - name: DB_POOL_SIZE
              value: "{{ db_pool_size }}"
            - name: RABBITMQ_HOST
              value: "ps2alerts-rabbitmq"
            - name: RABBITMQ_USER
              value: "ps2alerts"
            - name: RABBITMQ_PASS
              value: "{{ rabbitmq_pass }}"
            - name: RABBITMQ_VHOST
              value: "/ps2alerts"
            - name: RABBITMQ_QUEUE
              value: "{{ rabbitmq_queue }}"
            - name: RABBITMQ_PREFETCH
              value: "{{ rabbitmq_prefetch }}"
            - name: REDIS_HOST
              value: "{{ redis_host }}"
            - name: REDIS_PASS
              value: "{{ redis_pass }}"
            - name: REDIS_DB
              value: "{{ redis_db }}"
            - name: AGGREGATOR_ENABLED
              value: "false"
            - name: CRON_ENABLED
              value: "true"
            - name: LOGGER_TRANSPORTS
              value: "console"
            - name: INTERNAL_API_USER
              value: "{{ internal_api_user }}"
            - name: INTERNAL_API_PASS
              value: "{{ internal_api_pass }}"
